service: serverless-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  tracing:
    lambda: true
  tag: 
    Name: $(self:service)
    Environment: $(self:provider.stage)
    Department: dev
    Team: int-xmn
    Owner: Lucy.Tu
  environment:
    TABLE_NAME: testTable
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:524621635179:table/testTable"

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: index
         method: get
resources:
 Resources:
  testTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: testTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
plugins:
  - serverless-offline
  - serverless-dynamodb-local
